name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: pre-commit

  verify-apps:
    name: Build apps
    needs: pre-commit
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: ${{ matrix.runner-os }}
      framework: ${{ matrix.framework }}
      target-platform: Linux
      target-format: system
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "system", "3.10", "3.11", "3.12", "3.13", "3.14" ]
        framework: [ "toga", "pyside6", "pygame", "console" ]
        runner-os: [ "ubuntu-24.04", "ubuntu-24.04-arm" ]
        # Pygame and PySide6 haven't published 3.14 wheels yet.
        exclude:
          - python-version: "3.14"
            framework: pyside6
            runner-os: "ubuntu-24.04"
          - python-version: "3.14"
            framework: pyside6
            runner-os: "ubuntu-24.04-arm"
          - python-version: "3.14"
            framework: pygame
            runner-os: "ubuntu-24.04"
          - python-version: "3.14"
            framework: pygame
            runner-os: "ubuntu-24.04-arm"
