name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: "1"

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: pre-commit

  verify-apps:
    name: Build apps
    needs: pre-commit
    # TODO: Revert to main when .github#172 is merged
    uses: beeware/.github/.github/workflows/app-build-verify.yml@599f2fbb61c17aa94a962f26647f31a879a31052
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: ubuntu-latest
      framework: ${{ matrix.framework }}
      target-platform: Linux
      target-format: system
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "system", "3.9", "3.10", "3.11", "3.12", "3.13" ]
        framework: [ "toga", "pyside6", "pygame", "console" ]
        exclude:
          # PySide6 doesn't support Python 3.13 yet
          - python-version: 3.13
            framework: pyside6
